version: "3.7"
x-default-variables: &default-variables
  NEWSAPI_KEY: ${NEWSAPI_KEY}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PORT: ${POSTGRES_PORT}
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment: *default-variables
    ports: 
      - "80:8080"
    depends_on:
      - db
    links:
      - db
  db:
    environment: *default-variables
    image: "postgres:11.5"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/pgdata:/pgdata
  fetch:
    build:
      context: ./fetch
      dockerfile: Dockerfile
    depends_on:
      - db
    environment: *default-variables
    links:
      - db
      